<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I3EUG8M" ignored="3" name="Test" tests="1" failures="1" timestamp="2021-01-28T11:03:03 IST" time="0.174" errors="0">
  <testcase name="testCase4" time="0.07" classname="appium.framework.Demo1">
    <failure type="io.appium.java_client.service.local.InvalidServerInstanceException" message="The main Appium script does not exist at &amp;apos;C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\build\lib\main.js&amp;apos;">
      <![CDATA[io.appium.java_client.service.local.InvalidServerInstanceException: The main Appium script does not exist at 'C:\Users\Administrator\AppData\Roaming\npm\node_modules\appium\build\lib\main.js'
at io.appium.java_client.service.local.AppiumServiceBuilder.validatePath(AppiumServiceBuilder.java:131)
at io.appium.java_client.service.local.AppiumServiceBuilder.loadPathToMainScript(AppiumServiceBuilder.java:289)
at io.appium.java_client.service.local.AppiumServiceBuilder.createArgs(AppiumServiceBuilder.java:381)
at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:349)
at io.appium.java_client.service.local.AppiumDriverLocalService.buildService(AppiumDriverLocalService.java:87)
at appium.framework.Capability.startServer(Capability.java:45)
at appium.framework.Demo1.testCase4(Demo1.java:97)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCase4 -->
  <testcase name="testCase1" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase2" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- Test -->
